Update copyright lines
SeedV/SeedCalc pull request #15
Opened 2021-12-26 04:09 UTC by wixette

2021-12-26 07:34 UTC, codingpotato requested changes

2021-12-26 07:34 UTC, codingpotato commented on Assets/Src/Shaders/GridShader.shader
> +// Copyright 2021 The SeedV Lab.
```suggestion
// Copyright 2021-2022 The SeedV Lab.
```

2021-12-26 11:33 UTC, wixette commented on Assets/Src/Shaders/GridShader.shader
> +// Copyright 2021 The SeedV Lab.
Done

2021-12-28 12:29 UTC, wixette commented
@codingpotato Got time to take a look at this PR again?

2021-12-28 12:41 UTC, codingpotato approved these changes

2021-12-28 12:41 UTC, merged